version: '3'

services:
  web:
    image: kamolcu/phalcon-php71-fpm
    container_name: [project_name]_web
    restart: always
    volumes:
      - ./prod-server.conf:/etc/nginx/conf.d/server.conf
      - ./prod-php.ini:/etc/php/7.2/fpm/php.ini
      - /opt/src/[project_name]:/var/www/server
    working_dir: /var/www/server
    environment:
      - VIRTUAL_HOST=[project_name].com
      - LETSENCRYPT_HOST=[project_name].com
      - LETSENCRYPT_EMAIL=admin@[project_name].com
      - VIRTUAL_NETWORK=docker_network

networks:
  default:
    external:
      name: docker_network
