<?php

/**
 * Config
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-05-17, 15:23:25
 */
class Config extends BaseModel
{

    /**
     *
     * @var string
     * @Primary
     * @Column(column="key", type="string", length=100, nullable=false)
     */
    public $key;

    /**
     *
     * @var string
     * @Column(column="value", type="string", length=1000, nullable=true)
     */
    public $value;

    /**
     *
     * @var string
     * @Column(column="createdAt", type="string", nullable=true)
     */
    public $createdAt;

    /**
     *
     * @var string
     * @Column(column="updatedAt", type="string", nullable=true)
     */
    public $updatedAt;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("mainDb");
        $this->setSource("config");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'config';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Config[]|Config|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Config|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
